server:
  error.whitelabel.enabled: false
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
      javax:
        persistence:
          query.timeout: 90000
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
  banner:
    image:
      location: classpath:banner.png
      width: 100
      height: 15
      margin: 1

logging.config: classpath:logback-${ENV:development}.xml

logstash:
  url: http://127.0.0.1:31311
